### ISSUE TITLE
Metadata.rb needs to have a 'name'

### ISSUE THREAD

**Issue by arieplugge** [xanzy/chef-guard#40]
The metadata.rb file needs to have a name attribute which should match the repo name.
Perhaps also the presence of a metadata.json file messes up chef-guard? I delete the file also, so I cannot test it.

**Comment by arieplugge** [comment]
The error message is not indicative for the error:
ERROR: bad gateway
Response: Failed to upload <cookbookname>to the Supermarket: Multipart POST part 'tarball' must contain a README.

**Comment by svanharmelen** [comment]
@arieplugge maybe we should document this better, but for now this is indeed the case. It's probably possible to change this behaviour but this is actually due to how the Supermarket checks for a README when a cookbook is uploaded to the Supermarket. So the (not so indicative) error message is forwarded directly from the Supermarket itself.

Will add a label and leave the issue open for now, until I got a change to see if what/how we can improve anything for this.

**Comment by svanharmelen** [comment]
Let's not call this a bug, as it is correct that it works this way... But maybe we can improve/enhance the user experience a little here...

**Comment by svanharmelen** [comment]
As we are just returning the error received from the Supermarket, I don't think we can/should try to understand all possible errors coming from the Supermarket and change them in Chef-Guard.

So I will close this one as it is actually the Supermarket that should be returning a more sensible error message instead of Chef-Guard.
