### ISSUE TITLE
Running the cookbook

### ISSUE THREAD

**Issue by wingZero21** [xanzy/chef-guard#46]
Hi,

Quick one, when trying to run the cookbook it complains about trying to get the key from s3.

Is there anyway to ignore this bit, can we just comment out the s3 part?

Regards
Mark

Details:
[0m
ChefVault::Exceptions::KeysNotFound[0m
-----------------------------------[0m
chef-guard/chef.s3_keys could not be found[0m

**Comment by svanharmelen** [comment]
@wingZero21 if you want to let Chef-Guard check any cookbooks, it will need the keys (which can be found in either /etc/chef-server/chef-server-secrets.json (for Open Source Chef) or /etc/opscode/private-chef-secrets.json (for Enterpise Chef). So any specific reason you do not want to create a Chef Vault (instructions and example can be found here: https://github.com/xanzy/chef-guard-cookbook#usage) that contains the needed key and secret?

But I can add some checks around this part to make sure that if you leave the 'default['chef-guard']['vault']` attribute empty, it will skip this part without an error.

Still it would be nice to understand your use case, so I can better understand the issue with this part adn fix it in a (maybe) more generic way (as maybe others will have the same use case).

Thanks!

S.

// I'll ref this issue to a cross repo issue logged just now so this can also be found there: xanzy/chef-guard-cookbook#12

**Comment by wingZero21** [comment]
Hi,

We dont have the key's in S3 currently, so I guess some type of option to specify where the keys will be or to ignore the S3 option would be great.

**Comment by svanharmelen** [comment]
I'm really sorry, but I guess I don't understand what you are trying to say... If you have installed Chef (either open source Chef or Enterprise Chef) it will install the bookshelf for you by default.

The bookshelf is then used to store all uploaded cookbooks. So you need to have one in order to be able to work with Chef and cookbooks. The API they created for the bookshelf is compatible with the S3 API so you could configure and S3 storage as backend yourself if you would like.

In any case, Chef will then create those S3 keys for you as the ErChef API needs them to be able to access the bookshelf and upload and download cookbooks from it. So it sounds really strange that you don't have those keys... Maybe I'm just getting it wrong in which case I hope you can explain your setup in a little more detail.

Did you search for the secret files (.json) I pointed out earlier? As Chef would have saved the S3 info in that file for you...

**Comment by wingZero21** [comment]
Hi,

We dont want to put the keys into S3 is what were saying pretty much.

Not everyone uses Amazon :D

**Comment by svanharmelen** [comment]
But you don't put your keys into S3... And Amazon has nothing to do with this... Really. They are calles S3 keys, but they are the keys that are created BY CHEF during the installation of your Chef server. And the keys give access to your bookshelf which is an internal component of your Chef setup...

Maybe you could join the #chef-guard channel on freenode (IRC) so we can discuss this there. I believe you misinterpreted the meaning of S3 here. Again, no Amazon is involved (we also do not use that :smiley:) only Chef components which you will have once you have installed Chef on a server...

**Comment by sbotman** [comment]
With enterprise chef these keys can be found in: /etc/opscode/private-chef-secrets.json

there you will see a section:

```
  "bookshelf": {
    "access_key_id": "xxxxxx",
    "secret_access_key": "xxxxxx"
 }
```

This is the key information that you need.

Reason why we don't just read this file, is because it can also be named differently or be placed in another location.

Updates to the documentation will be done to clarify this more, so thank you for the question and hope that this will fix your problem.

**Comment by wingZero21** [comment]
Hey,

Yeah apologies I assumed that S3 was doing something to drag the keys from S3 Amazon. If its just adding the key's in that format from the chef server then its not a problem.

I am using Open Source Chef currently. Might be worth adding to the read me specifically what needs adding/amending before running the cookbook (I may have missed it originally)

Cheers

**Comment by svanharmelen** [comment]
We do have a little info about it, but indeed we should make this more clear. Thanks and let me know if you have any more/other issues with using the cookbook.

I'll leave this issue open until I got a change to update the readme to make this more clear.

**Comment by svanharmelen** [comment]
Fixed by PR xanzy/chef-guard-cookbook#15

**Comment by wingZero21** [comment]
Hi,

Just looking at the updated readme. Cheers for the update. Not really familiar with the vault, is this similar to the databags or something different.

Does this support using databags or do you definitely need to create it using the knife vault command.

Regards
Mark

**Comment by svanharmelen** [comment]
@wingZero21 Yes, currently this is only supported with vaults (open to PR's through :wink:). But the usage of a vault is actually pretty straight forward. See [here](https://github.com/Nordstrom/chef-vault) for some more info about how to set it up...

**Comment by wingZero21** [comment]
Hi,

Quick one again apologies. I have ran the command that you added to the readme to create the keys.

It seems to have created the keys however currently checking them they seem to be blank looking on the gui even though I did specify them on the command line as requested.

Any ideas on what I need to do for this.

Details:
[2014-10-21T16:09:26+01:00] ERROR: chef-guard/chef.s3_keys could not be found
[2014-10-21T16:09:26+01:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1) <err>: <args>: ('/usr/bin/chef-client', '--json-attributes', '/etc/chef/json_attributes.json')

Databag on chef server
bag Items  
chef.s3 Edit | Delete
chef.s3_keys    Edit | Delete

Regards
Mark

**Comment by svanharmelen** [comment]
@wingZero21 no problem at all! I'll have a look tomorrow, little busy today...

**Comment by svanharmelen** [comment]
@wingZero21 I just did some checking and the command should be good. Are both chef.s3 and chef.s3_keys items empty? And are you sure your search query is a good query that returns your Chef server(s)?

You could check that by running `knife search node "name:your-search-query"`

**Comment by wingZero21** [comment]
Hi,

Yeah I wanted to confirm on that, for the query that is run does that need to be the server that is running chef-guard or the main chef-server itself?

**Comment by svanharmelen** [comment]
Well... The server running Chef-Guard and the server running Chef, should actually be the exact same server. Please have a look at this [page](http://xanzy.io/projects/chef-guard/installation/installation.html) for more info and a picture of the setup.

**Comment by wingZero21** [comment]
Hi,

Ok so just to confirm you cant have the chef-guard server running separate to an existing chef-server? On the Diagram it hits chef-guard first and it does not say that it has to be on the same server just the calls that go to the chef server.

**Comment by svanharmelen** [comment]
I see what you mean... But the box labelled `Chef Server` is actually **not** your Chef server, but a single component of your Chef installation, being the ErChef API.

See [here](https://docs.getchef.com/server_components.html) for some more details about these components...

So in fact the diagram means to be showing that it's actually running on the same server.

That said, I think it would be possible to run CG on a separate server. Thinking about it I would think that all things that are needed are existing configuration options. You would however still have to edit your Nginx conf on your Chef server to [enable the flow to CG](http://xanzy.io/projects/chef-guard/installation/installation.html#enable-the-chef-guard-component-within-the-chef-server-config), so all calls (also from the web interface) are correctly forwarded to CG.

Personally I do not see why you would want to run CG on a dedicated server as it's a really light weight and stateless service. And since it's a single binary it doesn't change that much on your Chef server. But it would be a nice test to see if a setup like that works out of the box, so let me know if you hit any issues...
