### ISSUE TITLE
When editing a node Chef Guard commits the default attributes

### ISSUE THREAD

**Issue by Tech356** [xanzy/chef-guard#69]
Updating the normal attributes of a node, Chef Guard commits the default attributes. For example, running `knife node edit chf-mynode` returns the following:

```
{
  "name": "chf-mynode",
  "chef_environment": "myenv",
  "normal": {
    "tags": []
  },
  "run_list": [
    "recipe[windows]",
    "recipe[ohai]",
    "recipe[myrecipe]"
 ]
}
```

If I add attributes at the normal level and save.

```
{
  "name": "chf-mynode",
  "chef_environment": "myenv",
  "normal": {
    "myattr": {
      "sub1": "data1",
      "sub2": "data2"
    },
    "tags": []
  },
  "run_list": [
    "recipe[windows]",
    "recipe[ohai]",
    "recipe[myrecipe]"
  ]
}
```

Chef guard commits the default attributes, pulled from the cookbook on the last run, in addition to the normal attributes I just added. 

```
File: nodes/chf-mynode.json
@@ -1,10 +1,42 @@
 {
   "chef_environment": "myenv",
   "chef_type": "node",
-  "default": {},
+  "default": {
+    "chef_handler": {
+      "handler_path": "C:/Chef/handlers",
+      "root_group": "root",
+      "root_user": "root"
+    },
+    "myattr": {
+      "sub1": null,
+      "sub2": null
+    },
+    "ohai": {
+      "hints_path": "C:/chef/ohai/hints",
+      "plugin_path": "C:/chef/ohai_plugins",
+      "plugins": {
+        "ohai": "plugins",
+      }
+    },
+    "windows": {
+      "allow_pending_reboots": true,
+      "reboot_timeout": 60,
+      "rubyzipversion": null
+    }
+  },
   "json_class": "Chef::Node",
   "name": "chf-mynode",
   "normal": {
+    "myattr": {
+      "sub1": "data1",
+      "sub2": "data2"
+    },
     "tags": []
   },
   "override": {},
```

It seems to me that the default attributes should not be committed since they come from the cookbooks (Which should already be commited) and can change on the next run. Since Chef Guard does not update the default attributes after every run (and should not), the default attributes in the config repo will quickly become out of date and useless.

**Comment by svanharmelen** [comment]
@Tech356 this is actually by design. Whenever you make a change that is registered by CG, CG will first send your change to your Chef server and is the result is OK (no error occurred) it will save the complete current state of the object you just updated.

So what your seeing in the diff is the state of the object after your change was applied to the object. This should be fine and usable as backup/restore and for auditing purposes as it will be clear what changed.

Indeed the dynamic values could be outdated very quickly, but whenever you use this diff to restore the state of the object during it first run it will again set/update the dynamic values to there current values. So it will work as expected...

Closing this as a won't fix as it really by design to register the diff like this.

Thx!
